### ISSUE TITLE
[dcc32 Fatal Error] uWebSocket.pas(119): F1026 File not found: 'uLog.dcu'

### ISSUE THREAD

**Issue by edwinyzh** [pjde/delphi-jqmobile#1]
Hello,

Just discovered the project today, trying to compile, and got the following error:
`[dcc32 Fatal Error] uWebSocket.pas(119): F1026 File not found: 'uLog.dcu'`

I confirm in the src sub-folder there is not a file called `uLog.pas`.

**Comment by pjde** [comment]
It would have been referencing a logging window.

It is not needed so you can probably just remove the reference.




------ Original Message ------

**Comment by edwinyzh** [comment]
Thanks, it works.
